service: whatsapp-feedback-system
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, 'development'}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_WHATSAPP_NUMBER: ${env:TWILIO_WHATSAPP_NUMBER}
    EMAIL_HOST: ${env:EMAIL_HOST}
    EMAIL_PORT: ${env:EMAIL_PORT}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    FROM_EMAIL: ${env:FROM_EMAIL}
    TO_EMAIL: ${env:TO_EMAIL}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    MAX_RETRY_ATTEMPTS: ${env:MAX_RETRY_ATTEMPTS, '3'}

functions:
  webhookHandler:
    handler: index.handler
    events:
      - httpApi:
          path: /whatsapp
          method: post
      - httpApi:
          path: /send-survey
          method: get
    environment:
      FUNCTION_NAME: webhookHandler

  # Optional: Separate function for survey sending
  surveyHandler:
    handler: index.handler
    events:
      - schedule:
          rate: cron(0 10 * * ? *) # Daily at 10 AM
          input:
            type: "scheduled-survey"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
